/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pankis;

import paneles.menus.Ventas;
import paneles.menus.Recetas;
import paneles.menus.Inventario;
import paneles.menus.Dashboard;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author pedro
 */
public class inicio extends javax.swing.JFrame {
 
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
    
    
    // Configurar el Timer
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener la fecha y hora actual
                Date now = new Date();
                // Formatear la fecha y hora
                String formattedDate = dateFormat.format(now);
                String formattedTime = timeFormat.format(now);
                // Establecer el texto de los JLabels
                fecha.setText(formattedDate);
                hora.setText(formattedTime);
            }
        });
        
        
    /**
     * Creates new form menu
     */
    public inicio() {
        initComponents();
        setSize(1280, 740);
        setLocationRelativeTo(null);
        timer.start();
        Dashboard p= new Dashboard();
       
       p.setSize(1032, 720);
       p.setLocation(0, 0);
       
       contenido.removeAll();
       contenido.add(p);
       contenido.revalidate();
       contenido.repaint();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        boton_dashboard = new javax.swing.JButton();
        boton_inventario = new javax.swing.JButton();
        boton_ventas = new javax.swing.JButton();
        boton_recetas = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoo.png"))); // NOI18N

        fecha.setFont(new java.awt.Font("Coda", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Fecha");

        hora.setFont(new java.awt.Font("Coda", 0, 14)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 255, 255));
        hora.setText("Hora");

        boton_dashboard.setBackground(new java.awt.Color(0, 0, 0));
        boton_dashboard.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        boton_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        boton_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/dashboard/buton1.png"))); // NOI18N
        boton_dashboard.setBorderPainted(false);
        boton_dashboard.setContentAreaFilled(false);
        boton_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_dashboard.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/dashboard/buton2.png"))); // NOI18N
        boton_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_dashboardMouseClicked(evt);
            }
        });

        boton_inventario.setBackground(new java.awt.Color(0, 0, 0));
        boton_inventario.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        boton_inventario.setForeground(new java.awt.Color(255, 255, 255));
        boton_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/inventario/buton3.png"))); // NOI18N
        boton_inventario.setBorderPainted(false);
        boton_inventario.setContentAreaFilled(false);
        boton_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_inventario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/inventario/buton4.png"))); // NOI18N
        boton_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_inventarioMouseClicked(evt);
            }
        });

        boton_ventas.setBackground(new java.awt.Color(0, 0, 0));
        boton_ventas.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        boton_ventas.setForeground(new java.awt.Color(255, 255, 255));
        boton_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/ventas/buton5.png"))); // NOI18N
        boton_ventas.setBorderPainted(false);
        boton_ventas.setContentAreaFilled(false);
        boton_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_ventas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/ventas/buton6.png"))); // NOI18N
        boton_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_ventasMouseClicked(evt);
            }
        });

        boton_recetas.setBackground(new java.awt.Color(0, 0, 0));
        boton_recetas.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        boton_recetas.setForeground(new java.awt.Color(255, 255, 255));
        boton_recetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/recetas/buton7.png"))); // NOI18N
        boton_recetas.setBorderPainted(false);
        boton_recetas.setContentAreaFilled(false);
        boton_recetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_recetas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/recetas/buton8.png"))); // NOI18N
        boton_recetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_recetasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton_recetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fecha)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(hora)
                        .addGap(95, 95, 95))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(boton_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_recetas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1032, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_dashboardMouseClicked
       Dashboard p= new Dashboard();
       
       p.setSize(1032, 720);
       p.setLocation(0, 0);
       
       contenido.removeAll();
       contenido.add(p);
       contenido.revalidate();
       contenido.repaint();
       
    }//GEN-LAST:event_boton_dashboardMouseClicked

    private void boton_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_inventarioMouseClicked
        Inventario p= new Inventario();
       
       p.setSize(1032, 720);
       p.setLocation(0, 0);
       
       contenido.removeAll();
       contenido.add(p);
       contenido.revalidate();
       contenido.repaint();
       
    }//GEN-LAST:event_boton_inventarioMouseClicked

    private void boton_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ventasMouseClicked
        Ventas p= new Ventas();
       
       p.setSize(1032, 720);
       p.setLocation(0, 0);
       
       contenido.removeAll();
       contenido.add(p);
       contenido.revalidate();
       contenido.repaint();
    }//GEN-LAST:event_boton_ventasMouseClicked

    private void boton_recetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_recetasMouseClicked
        Recetas p= new Recetas();
       
       p.setSize(1032, 720);
       p.setLocation(0, 0);
       
       contenido.removeAll();
       contenido.add(p);
       contenido.revalidate();
       contenido.repaint();
    }//GEN-LAST:event_boton_recetasMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton boton_dashboard;
    private javax.swing.JButton boton_inventario;
    private javax.swing.JButton boton_recetas;
    private javax.swing.JButton boton_ventas;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
