/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles.funciones.inventario;

import conexionSQL.conexionSQL;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author pedro
 */
public class addslot extends javax.swing.JFrame {
private conexionSQL conexion;
    /**
     * Creates new form add
     */
    public addslot() {
        initComponents();
        setSize(465, 462);
        setLocationRelativeTo(null);
        
        
        conexion = new conexionSQL();

        // Obtener categorías y llenar el JComboBox
        List<String> categorias = conexion.obtenerCategorias();
        for (String categoria : categorias) {
            combo_categoria.addItem(categoria);
        }
        
        // Obtener categorías y llenar el JComboBox
        List<String> unidades = conexion.obtenerUnidades();
        for (String unidad : unidades) {
            combo_unidad.addItem(unidad);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundedTextField1 = new paneles.componentes.RoundedTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_unidad = new paneles.componentes.RoundedComboBox();
        combo_categoria = new paneles.componentes.RoundedComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roundedTextField2 = new paneles.componentes.RoundedTextField();
        roundedTextField3 = new paneles.componentes.RoundedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        boton_cancelar = new paneles.componentes.FButton();
        boton_agregar = new paneles.componentes.FButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/cerrar/cerrar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/cerrar/cerrar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 10, 40, 40);

        jLabel1.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FECHA CADUCIDAD:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 360, 170, 20);

        jLabel2.setFont(new java.awt.Font("Coda", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGREGAR SLOT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 30, 210, 50);

        roundedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(roundedTextField1);
        roundedTextField1.setBounds(180, 290, 230, 40);

        jLabel3.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INGREDIENTE:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 140, 20);

        combo_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_unidadActionPerformed(evt);
            }
        });
        jPanel1.add(combo_unidad);
        combo_unidad.setBounds(180, 190, 230, 40);

        combo_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_categoriaActionPerformed(evt);
            }
        });
        jPanel1.add(combo_categoria);
        combo_categoria.setBounds(180, 140, 230, 40);

        jLabel4.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CATEGORÍA:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 150, 100, 20);

        jLabel5.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("UNIDAD:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 200, 80, 20);

        roundedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(roundedTextField2);
        roundedTextField2.setBounds(180, 90, 230, 40);

        roundedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(roundedTextField3);
        roundedTextField3.setBounds(180, 240, 230, 40);

        jLabel6.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CANTIDAD:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 250, 100, 20);

        jLabel7.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PROOVEDOR:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 300, 120, 20);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(220, 350, 190, 30);

        boton_cancelar.setText("CANCELAR");
        boton_cancelar.setFillClick(new java.awt.Color(0, 0, 0));
        boton_cancelar.setFillOriginal(new java.awt.Color(204, 0, 0));
        boton_cancelar.setFillOver(new java.awt.Color(0, 0, 0));
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cancelar);
        boton_cancelar.setBounds(100, 400, 110, 40);

        boton_agregar.setText("AGREGAR");
        boton_agregar.setFillClick(new java.awt.Color(0, 0, 0));
        boton_agregar.setFillOriginal(new java.awt.Color(0, 153, 0));
        boton_agregar.setFillOver(new java.awt.Color(0, 0, 0));
        jPanel1.add(boton_agregar);
        boton_agregar.setBounds(230, 400, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
       dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    private void combo_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_categoriaActionPerformed

    private void combo_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_unidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_unidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addslot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addslot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private paneles.componentes.FButton boton_agregar;
    private paneles.componentes.FButton boton_cancelar;
    private paneles.componentes.RoundedComboBox combo_categoria;
    private paneles.componentes.RoundedComboBox combo_unidad;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private paneles.componentes.RoundedTextField roundedTextField1;
    private paneles.componentes.RoundedTextField roundedTextField2;
    private paneles.componentes.RoundedTextField roundedTextField3;
    // End of variables declaration//GEN-END:variables
}
