/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles.funciones.inventario;

import conexionSQL.conexionSQL;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class addunidad extends javax.swing.JFrame {
    private conexionSQL conexion;
    /**
     * Creates new form add
     */
    public addunidad() {
        initComponents();
        setSize(465, 270);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prefijo_unidad = new paneles.componentes.RoundedTextField();
        boton_agregar = new paneles.componentes.FButton();
        jLabel4 = new javax.swing.JLabel();
        nombre_unidad = new paneles.componentes.RoundedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/cerrar/cerrar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/cerrar/cerrar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 10, 40, 40);

        jLabel2.setFont(new java.awt.Font("Coda", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGREGAR UNIDAD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 30, 240, 50);

        jLabel3.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PREFIJO:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 150, 90, 20);

        prefijo_unidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prefijo_unidad.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jPanel1.add(prefijo_unidad);
        prefijo_unidad.setBounds(160, 140, 230, 40);

        boton_agregar.setText("AGREGAR");
        boton_agregar.setFillClick(new java.awt.Color(0, 0, 0));
        boton_agregar.setFillOriginal(new java.awt.Color(0, 153, 0));
        boton_agregar.setFillOver(new java.awt.Color(0, 0, 0));
        boton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_agregar);
        boton_agregar.setBounds(190, 200, 110, 40);

        jLabel4.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOMBRE:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 100, 140, 20);

        nombre_unidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_unidad.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        jPanel1.add(nombre_unidad);
        nombre_unidad.setBounds(160, 90, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregarActionPerformed
        conexion = new conexionSQL();
           
               String nombreUnidad = nombre_unidad.getText().trim();
                String prefijoUnidad = prefijo_unidad.getText().trim();
                if (!nombreUnidad.isEmpty() && !prefijoUnidad.isEmpty()) {
                    boolean exito = conexion.agregarUnidad(nombreUnidad, prefijoUnidad);
                    if (exito) {
                        JOptionPane.showMessageDialog(null, "Unidad agregada con éxito.");
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar la unidad.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
                }
    }//GEN-LAST:event_boton_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addunidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private paneles.componentes.FButton boton_agregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private paneles.componentes.RoundedTextField nombre_unidad;
    private paneles.componentes.RoundedTextField prefijo_unidad;
    // End of variables declaration//GEN-END:variables
}
