/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles.menus;

import paneles.funciones.inventario.addaccidente;
import paneles.funciones.inventario.addcategoria;
import paneles.funciones.inventario.addslot;
import paneles.funciones.inventario.addunidad;

/**
 *
 * @author pedro
 */
public class Inventario extends javax.swing.JPanel {

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        raccidente = new paneles.componentes.FButton();
        boton_buscar = new paneles.componentes.RoundedTextField();
        jLabel1 = new javax.swing.JLabel();
        tabla = new paneles.componentes.TablePanel();
        jButton1 = new javax.swing.JButton();
        addboton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1032, 720));
        jPanel1.setLayout(null);

        raccidente.setText("REGISTRAR ACCIDENTE");
        raccidente.setFont(new java.awt.Font("Coda", 0, 14)); // NOI18N
        raccidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raccidenteActionPerformed(evt);
            }
        });
        jPanel1.add(raccidente);
        raccidente.setBounds(340, 50, 174, 39);

        boton_buscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boton_buscar.setText("Buscar");
        boton_buscar.setFont(new java.awt.Font("Coda", 0, 18)); // NOI18N
        boton_buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                boton_buscarFocusLost(evt);
            }
        });
        boton_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_buscarMouseClicked(evt);
            }
        });
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar);
        boton_buscar.setBounds(770, 50, 210, 36);

        jLabel1.setFont(new java.awt.Font("Coda", 0, 48)); // NOI18N
        jLabel1.setText("Inventario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 50, 215, 36);
        jPanel1.add(tabla);
        tabla.setBounds(0, 100, 1030, 186);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajustar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ajustar(1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 50, 40, 40);

        addboton.setBackground(new java.awt.Color(255, 255, 255));
        addboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-boton.png"))); // NOI18N
        addboton.setContentAreaFilled(false);
        addboton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addboton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-boton(2).png"))); // NOI18N
        addboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbotonActionPerformed(evt);
            }
        });
        jPanel1.add(addboton);
        addboton.setBounds(260, 50, 40, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-búsqueda-32.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-búsqueda-32(1).png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(980, 50, 40, 40);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1032, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void raccidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raccidenteActionPerformed
        addaccidente p= new addaccidente();
        p.setVisible(true);
    }//GEN-LAST:event_raccidenteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbotonActionPerformed
        addslot p= new addslot();
        p.setVisible(true);
    }//GEN-LAST:event_addbotonActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed

    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_buscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boton_buscarFocusLost
        if(boton_buscar.getText().isEmpty()){
        boton_buscar.setText("Buscar");
        
        }
    }//GEN-LAST:event_boton_buscarFocusLost

    private void boton_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_buscarMouseClicked
              if("Buscar".equals(boton_buscar.getText())){
            boton_buscar.setText("");
        }else if (boton_buscar.getText().isEmpty()) {
    boton_buscar.setText("Buscar");
}
    }//GEN-LAST:event_boton_buscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addboton;
    private paneles.componentes.RoundedTextField boton_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private paneles.componentes.FButton raccidente;
    private paneles.componentes.TablePanel tabla;
    // End of variables declaration//GEN-END:variables
}
